services:
  scrap:
    build: .
    env_file:
      - .env
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PORT: ${POSTGRES_PORT}

  metabase-db:
    image: postgres:16
    container_name: metabase-db
    restart: always
    environment:
      POSTGRES_USER: ${MTBPOSTGRES_USER}
      POSTGRES_PASSWORD: ${MTBPOSTGRES_PASSWORD}
      POSTGRES_DB: ${MTBPOSTGRES_DB}
    ports:
      - "${MTBPOSTGRES_PORT}:${DB_PORT}"  # Cambiado para evitar conflicto de puerto
    volumes:
      - metabase-data:/var/lib/postgresql/data
      - ./metabaseDBMig:/docker-entrypoint-initdb.d

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${MTBPOSTGRES_DB}
      MB_DB_PORT: ${DB_PORT}
      MB_DB_USER: ${MTBPOSTGRES_USER}
      MB_DB_PASS: ${MTBPOSTGRES_PASSWORD}
      MB_DB_HOST: metabase-db
    depends_on:
      - metabase-db

volumes:
  metabase-data: