version: '3'

services:
  fastapiDB:
    image: postgres:13
    env_file: .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d fastapi -U fastapi"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build: .
    # command: > 
    #   sh -c "python create_tables.py &&
    #          uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      fastapiDB:
        condition: service_healthy
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  postgres_data: