name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Push to Ubuntu Server
      run: |
        ssh -o StrictHostKeyChecking=no root@147.182.254.71 '
        cd Arqui_Alta_Disponibilidad_Tarea_2 &&
        git pull origin main &&
        docker compose down &&
        docker compose up --build -d
        '
      env:
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}